### ISSUE TITLE
Logo Design Offer For dashbug

### ISSUE THREAD

**Issue by iqbalhood** [jelic98/dashbug#1]
Hello Sir. I'm a UI/UX and Graphics Designer. who has contacted you via email last week.
**These are my logo proposal** for your application.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

![dashbug](https://user-images.githubusercontent.com/1563756/42919619-06872aa4-8b3d-11e8-9248-06eca4803524.jpg)

**Comment by jelic98** [comment]
Hello,

Your design is great! Thank you very much. How about replacing desktop with a mobile phone? As for logo format, SVG would be great. Shall I mention you in README?

Regards,
Lazar Jelic

**Comment by iqbalhood** [comment]
Hello @jelic98, 
This is my improvement for the last logo concept.

![dahbug rev1](https://user-images.githubusercontent.com/1563756/42976315-172f1d40-8beb-11e8-9193-0fcb16cf46e9.jpg)

**Comment by iqbalhood** [comment]
Okay, No Problem, this link for the png and editable file you need

https://drive.google.com/drive/folders/1GFnQUen_tfVfB-zhKakNXv4uOIqOVjfO?usp=sharing

**Comment by jelic98** [comment]
Thanks! Your logo is added. I've mentioned you in README.
