### ISSUE TITLE
Offer To Copywrite 

### ISSUE THREAD

**Issue by Kelita** [jelic98/dashbug#2]
Hello, I notice some document such as FAQs, About Us and Privacy Policy is missing. I would love to contribute them to your project. 
Please let me know if you want me to do so.

**Comment by jelic98** [comment]
Hi Kelita, feel free to make a pull request when those documents are done. Thank you!

**Comment by Kelita** [comment]
I would need details on how you collect and use personal datas of users when the make sure of the app.

**Comment by Kelita** [comment]
Hello, I have been working on it, but for me to further continue my writing, I will need an apk of the app. I am not a developer, so I am unable to assemble the app. 
I have also been a little bit busy at my end that why there is such a little delay.
Please let me know if you can provide the apk of it

**Comment by jelic98** [comment]
There is no APK. Dashbug is a library which is included in other APK's.

**Comment by Kelita** [comment]
Okay! I would also like to know if the library access the MAC address for the phone's Wifi or Bluetooth adapter and also the device ID of the phone (IMEI for GSM/ MEID or ESN for CDMA).

**Comment by Kelita** [comment]
Sorry for the delay in response.

**Comment by jelic98** [comment]
No, library does not access MAC address or anything else that could identify user or device.

**Comment by Kelita** [comment]
Hello, I am done with the Privacy Policy. Please do well to check if there is any need for correction before I make a pull request. 

https://docs.google.com/document/d/1HbnvdJca9CfHRqrDRVQlF0sn0yuxIfyLaJTnbrXjYMk/edit?usp=sharing

**Comment by jelic98** [comment]
Looks good. Just put my email address (lazarjelic98@gmail.com) at the end.

**Comment by Kelita** [comment]
I have made a pull request. Thanks

**Comment by jelic98** [comment]
PR is Merged. I'll close this issue now.
